Incentive curve
BabelFishProtocol/babelfish-phase-1 pull request #80
Opened 2022-12-29 10:37 UTC by dharkmattr

2023-01-11 10:45 UTC, jameshowlett977 requested changes
Please add tests for MappingAddressToUint256, all other comments related to this contract are minor, we can leave as is, but should be aware of.

2023-01-11 10:45 UTC, jameshowlett977 commented on contracts/masset/Masset.sol
> +        mintPenalty(_basset, bassetQuantity, _recipient);
I haven't found a transfer of XUSD from the user's account as supposed according to spec, but we mint tokens to RewardManager.

2023-01-11 10:45 UTC, jameshowlett977 commented on contracts/masset/RewardManager.sol
> +    function setFactor(uint256 _factor) external onlyOwner {
_BabelFish Bitocracy should be able to add and remove addresses from an "incentive administrator" list. Every address that is on this list is an "incentive administrator"._

I think we need an admin role, admins should be able to invoke "setFactor" and "setTargetWeights".

2023-01-11 10:45 UTC, jameshowlett977 commented on contracts/masset/RewardManager.sol
> +        reward = reward < available ? reward : available;
Does it mean no rewards for the user even if he deserves it just because we don’t have enough balance on RewardManager?
Shouldn't we save rewards for users in order to withdraw later when funds are added?

2023-01-11 10:45 UTC, jameshowlett977 commented on contracts/masset/RewardManager.sol
> +        XUSD.transfer(_recipient, reward);
Please add "require("

2023-01-11 10:45 UTC, jameshowlett977 commented on test/RewardManager.spec.ts
> +const testCases = [
Please add unit tests for all functions and negative cases for already added.

2023-01-11 10:45 UTC, jameshowlett977 commented on contracts/helpers/MappingAddressToUint256.sol
> +contract MappingAddressToUint256 is Ownable {
Please add tests for this contract.

2023-01-16 10:08 UTC, dharkmattr commented on contracts/helpers/MappingAddressToUint256.sol
> +            r[i] = values[keys[i]];
I don't think so.... if the key is removed then the value will not be returned.

2023-01-16 10:09 UTC, dharkmattr commented on contracts/helpers/MappingAddressToUint256.sol
> +        for(uint i=0; i < keys.length; i++) {
No, order is not important.... fixed.

2023-01-16 10:15 UTC, dharkmattr commented on contracts/masset/BasketManager.sol
> +                bassetsArray[i] = bassetsArray[bassetsArray.length-1];
is a redundant a[i] = a[i] more expensive than testing for i!=a.length-1 ?
I'm not sure....
At any rate this function is not likely to be called often, so gas cost is not important.

2023-01-16 10:16 UTC, dharkmattr commented on contracts/masset/Masset.sol
> +        mintPenalty(_basset, bassetQuantity, _recipient);
instead of transferring from the user's account, we burn all the XUSD and then mist the reward directly to the reward manager. I think this is the same thing, and it makes the logic much more simple.

2023-01-16 10:18 UTC, dharkmattr commented on contracts/masset/RewardManager.sol
> +    function setFactor(uint256 _factor) external onlyOwner {
mmm... why do we not use the same multisig for this as all the other parameters in the system? I don't trust any one person to set the factor or the weights, in case there's a large amount of funds in the reward manager.

2023-01-16 10:21 UTC, dharkmattr commented on contracts/masset/RewardManager.sol
> +        reward = reward < available ? reward : available;
The design was that if the funds run out we just don't incentivize. The UI will reflect this so nobody will expect a reward and not get it. If we save negative amounts and allow them to be withdrawn later it will cause a run on the funds when they come in, which I think is unfair and ungainly. Also, no such UI has been planned (to withdraw rewards at a later time).

2023-01-16 10:25 UTC, jameshowlett977 commented on contracts/helpers/MappingAddressToUint256.sol
> +            r[i] = values[keys[i]];
You're right.

2023-01-16 10:26 UTC, jameshowlett977 commented on contracts/masset/Masset.sol
> +        mintPenalty(_basset, bassetQuantity, _recipient);
agree

2023-01-16 10:27 UTC, jameshowlett977 commented on contracts/masset/RewardManager.sol
> +    function setFactor(uint256 _factor) external onlyOwner {
The spec should be updated then.

2023-01-16 10:30 UTC, jameshowlett977 commented on contracts/masset/RewardManager.sol
> +        reward = reward < available ? reward : available;
Got it, just make sure UI clearly tells about available reward.

2023-01-16 16:44 UTC, dharkmattr commented on contracts/masset/RewardManager.sol
> +    function setFactor(uint256 _factor) external onlyOwner {
It just occurred to me if we want this feature we can just set up a multisig with a 1 signer threshold and set bitocracy as its owner. So this capability is not in the scope of this PR.

2023-01-17 14:20 UTC, dharkmattr commented on contracts/masset/RewardManager.sol
> +    function setFactor(uint256 _factor) external onlyOwner {
light agrees to change the spec

2023-01-19 13:27 UTC, ororopickpocket reviewed
So far I only reviewed MappingAddressToUint256. I added a few comments for discussion.
I will continue the review later and/or tomorrow.

2023-01-19 13:27 UTC, ororopickpocket commented on contracts/helpers/MappingAddressToUint256.sol
> +contract MappingAddressToUint256 is Ownable {
is there a reason why you're not using open zeppelins enumerable map for this? it does support address => uint 
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/structs/EnumerableMap.sol

2023-01-19 13:27 UTC, ororopickpocket commented on contracts/helpers/MappingAddressToUint256.sol
> +    mapping(address => bool) private flags;
Is it important to have the flag? 
As i understand it, you're using the flag only to know which key has a value set. 
Why not just check if values[address] == 0 ?
Do you need to know if an address is consciously mapped to 0?

2023-01-19 13:27 UTC, ororopickpocket commented on contracts/helpers/MappingAddressToUint256.sol
> +        for(uint i=0; i<r.length; i++) {
depending on the number of keys this could become a very long loop up to the point where it cannot be processed in a single transaction. there should be a safeguard either by limiting the length of `keys` or by limiting the number of iterations here or by allowing the caller to pass start and end indexes. 
should you decide to do none of these because it seems not important to you in this case, at least add a comment in the function documentation informing developers that this needs to be considered.

2023-01-19 13:27 UTC, ororopickpocket commented on contracts/helpers/MappingAddressToUint256.sol
> +        for(uint i=0; i < keys.length; i++) {
again, this can become very expensive or impossible to execute if `keys` becomes too large. 
removing could be cheaper if you would keep an index. the index could be a mapping (address => uint) which lets you know at which point in the array, the key is stored. if you start counting the indexes from 1, you can replace the flag mapping with it, because then you can check if a key has been set by looking up its index (index 0 would mean not set).

2023-01-19 15:01 UTC, ororopickpocket reviewed
This is the review of Masset.sol only. The review of the RewardsManager is still outstanding.

2023-01-19 19:03 UTC, dharkmattr commented on contracts/helpers/MappingAddressToUint256.sol
> +    mapping(address => bool) private flags;
yes, a value = 0 is not the same as a token doesn't exist. I could have used a +1 trick, so that 0 = n/a and 1 = 0, but I think making the code less readable is not worth the gas gained from such optimization for small number of values

2023-01-19 19:04 UTC, dharkmattr commented on contracts/helpers/MappingAddressToUint256.sol
> +        for(uint i=0; i < keys.length; i++) {
removing a token is very rare. Actually, I don't even think it will ever happen

2023-01-19 19:08 UTC, dharkmattr commented on contracts/masset/BasketManager.sol
> +    function getBalanceInMasset(address _massetAddress, address _bassetAddress) public view returns (uint256) {
Well, every token can in principal have a different precision. This function gives you the balance of a basset in masset units. The code can be quite complex at times because every calculation has to convert amounts from basset units to masset units and vice versa.

In retrospect, all of the tokens we've ever had, had 18 digit precision, so this code can be simplified by removing all of this... this is a topic for future discussion.

2023-01-25 09:09 UTC, dharkmattr commented on contracts/helpers/MappingAddressToUint256.sol
> +contract MappingAddressToUint256 is Ownable {
I have philosophical objections to their implementation. I think it's unduly complicated, and I strongly believe complicated code === insecure code. I'm suspicious of oenzeppelin because of their horrible horrible upgradable proxy pattern. In the beginning I chose to use it because I thought "it's from openzeppelin so it must be good", but I'm regretting that choice almost daily now.

2023-01-30 12:09 UTC, ororopickpocket requested changes
Please check the math and add actual test cases for the reward and penalty calculations.
Also, natspec documentation would be nice.

2023-01-30 12:09 UTC, ororopickpocket commented on contracts/masset/RewardManager.sol
> +            factor.mul(dsqrAfter - dsqrBefore).div(tokens.length).div(ONE) :
this appears to be even more incorrect, because you're dividing by tokens.length which you already did in getAverageDsqrs

2023-01-30 12:50 UTC, dharkmattr commented on contracts/masset/RewardManager.sol
> +            factor.mul(dsqrAfter - dsqrBefore).div(tokens.length).div(ONE) :
Since factor is an arbitrary number to be determined by trial and error, it doesn't really matter. The question is if factor is defined in total or per stable-coin.

2023-02-07 09:34 UTC, dharkmattr commented on contracts/masset/BasketManager.sol
> +    function getBalanceInMasset(address _massetAddress, address _bassetAddress) public view returns (uint256) {
@ororopickpocket your thoughts?

2023-03-20 11:28 UTC, ororopickpocket commented on contracts/masset/RewardManager.sol
>      function getRewardForDeposit(
why make this one external if you're calling it internally as well?
why not public ?

2023-03-20 11:28 UTC, ororopickpocket commented on contracts/masset/RewardManager.sol
> +        reward = reward < _sum ? reward : _sum;
what's the purpose of this line?
I see that it's capping the maximum reward to the basset amount being deposited, but i don't see this on the spec.

2023-03-20 11:28 UTC, ororopickpocket commented on contracts/masset/Masset.sol
> +    **/
payReward is called by `onTokensMinted` and `_mintTo`. The first calls it after the basset is already transferred to the contract, the latter before it is transferred. This affects the outcome of `getAverageDsqrs`. Hadn't you planned to change this? Am I missing something?

2023-03-29 09:01 UTC, dharkmattr commented on contracts/masset/Masset.sol
> +    **/
I put this correction in a separate PR and sent it to you. I only now realized you must have missed it, sorry for not communicating more clearly.

2023-04-13 22:10 UTC, koirikivi commented on contracts/masset/Masset.sol
> +    function migrateToV4() public {
Just noticed this, but is it intentional that anyone can migrate?

2023-05-25 14:02 UTC, dharkmattr commented on contracts/masset/Masset.sol
> +    function migrateToV4() public {
yes, this can only happens once and we don't care who calls it as long as it gets called.

2023-05-25 14:05 UTC, dharkmattr commented on contracts/masset/RewardManager.sol
> +        reward = reward < _sum ? reward : _sum;
It's here just in case. In practice there's a maximum possible reward parameter that will never be over 100%. If this is not in the spec we should update the spec.

2023-08-30 09:58 UTC, merged