added functions to allow for bonus manager
BabelFishProtocol/babelfish-phase-1 pull request #83
Opened 2023-09-28 13:17 UTC by dharkmattr

2023-10-03 13:55 UTC, tjcloa commented
- No natspec provided - losing automatic docs generation option and makes it more difficult to review - no explicit intention  
- No unit tests tests - would facilitate review too

2023-10-05 06:21 UTC, night-pm reviewed
Most of the comments are related to gas savings.

2023-10-05 06:21 UTC, night-pm commented on contracts/masset/BonusManager.sol
> +        for(uint i=0; i<tokens.length; i++) {
Cache the length value of array. Also it's cost saving to use ++i.

2023-11-10 13:50 UTC, night-pm approved these changes
LGTM

2023-11-10 21:58 UTC, tjcloa commented
1. CI is failing - check tests
2. see inline comments

2023-11-10 22:00 UTC, tjcloa requested changes
pls address comments

2023-11-10 22:00 UTC, tjcloa commented on contracts/masset/BonusManager.sol
> +        require(token.transfer(owner(), _amount), "transfer failed");
recommendation: use OZ SafeERC20.safeTransfer to support tokens that return no value (and instead revert or throw on failure), non-reverting calls are assumed to be successful

2023-11-10 22:00 UTC, tjcloa commented on contracts/masset/BonusManager.sol
> +        return bonus;
what if bonus > balance here?

2023-11-14 09:32 UTC, dharkmattr commented on contracts/masset/Masset.sol
> +        bonusManager = IBonusManager(0);
Yes, the bonus manager will cannot be set before the masset is upgraded, and the migrate function is part of the migration script.

2023-11-14 09:35 UTC, dharkmattr commented on contracts/masset/Masset.sol
> +    function getBonusManager() external view returns (address) {
Address is omitted to be consistent with the naming in this file, eg getBasketManager, getToken etc

2023-11-14 20:45 UTC, tjcloa approved these changes

2023-12-12 09:01 UTC, merged